os: osx
language: swift
osx_image: xcode10.1

before_install:
  - brew tap bazelbuild/tap
  - brew tap-pin bazelbuild/tap
  - brew install bazel

script:
  - bazel version
  - bazel build //:tulsi
  - bazel test //src/TulsiGeneratorTests --test_output=errors --nocheck_visibility
  - bazel test //src/TulsiGeneratorIntegrationTests --test_output=errors --nocheck_visibility
